name: Print Name from Environment Variable (dev)

on:
  push:
    branches:
      - "**"

jobs:
  hello:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Print
        run: echo "MY_SECRET='${{ vars.MY_NAME }}'" 
